#let cv_theme = (
  colors: (
    accent: rgb("#dc7964"),
    header_text: white,
    text: rgb("#111111"),
    muted: rgb("#4b4b4b"),
    meter_empty: rgb("#cccccc"),
  ),
  fonts: (
    body: "Liberation Sans",
  ),
  sizes: (
    body: 8.75pt,
    name: 26pt,
    section_heading: 16.5pt,
    sidebar_heading: 9.5pt,
    meta: 7.8pt,
    note: 7pt,
  ),
  spacing: (
    page_x: 28pt,
    page_top: 24pt,
    page_bottom: 23pt,
    header_height: 96pt,
    header_inset: 9pt,
    avatar: 78pt,
    header_gutter: 15pt,
    after_header: 13pt,
    column_gutter: 20pt,
    body_leading: 5pt,
    compact_leading: 3.3pt,
    heading_below: 6pt,
    section_gap: 6pt,
    entry_gap: 5pt,
    project_gap: 6pt,
  ),
  layout: (
    sidebar_width: 29%,
  ),
)
